language: ruby
jdk:
- oraclejdk8
sudo: false
rvm:
- 2.3.1
before_install:
- openssl aes-256-cbc -K $encrypted_a45e2efa4ba5_key -iv $encrypted_a45e2efa4ba5_iv
  -in etc/secrets -out ../secrets.tar -d
- "(cd ../ && tar xvf secrets.tar)"
- chmod 600 ../release.asc
- gpg --import ../release.asc
install:
- rvm use 2.3.1
- gem install bundler
- bundle install
script: buildr clean package mcrt:publish_if_tagged
git:
  depth: false
env:
  global:
  - secure: dfVUTCga9fBV6i5SHl1lkmKUntCnJJJvq2GPAFMI/uREHZMCvLPi+USHp23SNJBx4yG1j0AXytSoIwwxNIQY7zzlbde6/rYS6IqKyjQt3TXfCVk8IrjiGcw/PORXAad25U5MS4JYykOEPfRz+Oh+4L5ucoxjaDINf5GYfB8dbWMunHEufkjJsB/LRa+LgJkDmzjLTZNUN8BiGwagqUB4VjrVADEydf0C+GpUTnprOgqXq/fuvVj6hNma9/GWkVPBQLvi8VUY81Ny9lxT6Jcblygo7L01oArhfCrFxaAIJVSqgfYKwe4XL4u06YPKdMsKtUfKsp5FtIIjKALhWJzOxQi+3aMThkJtpMxtNVa+1sUSgz+owMGpd704k4xdsWMEY+H9NlEHyZXvSXlLNdAVOCdAIquMk76LFVgSICW8Gcpbz0yFa9OqlVHnuDkXD+ITpoPgwzsYBwsKya7rgFmYQ7tdeHJ1R0DnEwUuAi8RORerPSW/dz+/VJQa0X7qxYl7GpFa9oggn5HDZk+zR8/dd3tQSE1lVU8wen9PyaUVyYFxqKSDrebtEQhHYmiNwBFEmOmwS8ZbnHJAyqQeXAITfEiFSRGxZzWcAmv+q28RvcpfX1MHAUdEjBfi2bYEzXdleCNxIR3U3znXl8qePst+zkn/vSqvH97d7bagDUbk/2k=
  - secure: b4DIS0WcJlaemMTlyBgnslyFn/QJxey9yYEGJB2zTdsApYRt1+WI//4bf9uV1SoPm0J+5HTw5TzisS7bX+S8/qHJ1qVfXDwnTwvXTScjFr1OzmXGXyGrzC3yrxvmv+o3aq6cP27CRLtcQj6l3gmMM1Dd5MwJyuQPmf4MtDF5/1zH+XGqBWL11HRJar0zoa28Fq9k0YJOljb5IxnD4Ehlv9K1TcZTwNDONbAx+M8QjTMcpwdidWqEjiwxDG2QKwE3e+emtwWdg4V+ndQHv3CIfRWByUzki0zB+Jb4+shF550UkLOA/3KXqvU81du3TqgyLX9uVmp1hLBXGyo2OYjVfKwi80xkh9AT9VRGlKRPTjya+tG3z1CDjFuc7+lDSMFCGN/dOzcdXzDf94ziCWpn9OT1Oo3rsGGLp752yWEF6lV54KjBaA6TqkcVYIbjWtxRtHHJLQ+/1G9Afae819G++kZbYyxb8+f/mIV2nD85BHmccIdb3tjGBkpdtcXEG2QdnJzytkOyPhHsdJ8E4sj1VBmo7O0I4oCLXAxnZihLzu1qhEx6bEZn9w2kWKo81CQEv39K51j3mACon4fNB3+CRj4iAos8DpNkvOXwjVZjjT831B+SqKhDBM2TaLayslSlJpST2YdAFWPXxJM2T1pCwbAatgqTKWPb3Yv/qwLPqws=
  - secure: 17NsPGltg34jtzyiHuf27zzRVGje19GmFEBNkzbxgwdisGCHH941PToRMJymyBbWhLHmsmuxSNRaS7jiF0PQ3rniVAFKm7O8h8lyfCgnW0IZwafb/D4mrKeuRNowTp9tYu0joeRY1BFpn79j9Ca67lqVQ5II2FQiiOgfBYDWr8g0z+hTHe+fZWbH3i4Vs7KSaxXx9PrOgP+0YCZTRFCfbAooLhhq+ASLiItGXhloIyoba8dN8qGB07E6lEUEydD8a2TOzWQ38QiINlfL9lBWJdb2sbf+3t2GEDqAp6Ag8G3sPQbRIqUvCkWG8qmf+jKcF1sQBBsKuFFqdQy2IkLKBBhvwjofVpOw2FhF6s3AQYQlp6HQ6W/qzP6beUpIL3Vha+W74+Wb3vdc+Fahj6CBKV9KA+m1OSp39OCIQArHInQ3QKY8mhlpKkCqq5o01M3MtlWB43kl5wBq9ODc9GzFEK3FWQ5IXq0Z+Wt4x9wbkD7JEO3w0CCyE9Vktxw1IphcI5BtknWQN9irHpKuUnu9pavTqi2rBE6lNBIlR88CdUXRWkMu9N8h82xNRD6G8ijfkMv/n59IbpCuur9c/22LgwME8TCYkPQqZxbZaHhwxbMjIQDBeC3byxbNXpUXsBOI9C+Z/Ej+rN0qo7r2U+GCYqNFpKN+VCDyB5cBiUtOc2Y=
