repositories:
  remote:
   - https://stocksoftware.jfrog.io/stocksoftware/maven2
   - https://repo.maven.apache.org/maven2

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.14

  dagger_core: com.google.dagger:dagger:jar:2.25.2
  dagger_core_sources: com.google.dagger:dagger:jar:sources:2.25.2
  dagger_gwt: com.google.dagger:dagger-gwt:jar:2.25.2
  javax_inject: javax.inject:javax.inject:jar:1
  javax_inject_sources: javax.inject:javax.inject:jar:sources:1
